frr defaults traditional
hostname spine1
log syslog informational
service integrated-vtysh-config
!
interface lo
 ip address 10.0.0.1/32
!
interface eth1
 description "Link to leaf1"
 ip address 10.1.1.0/31
 ip ospf network point-to-point
 ip ospf hello-interval 10
 ip ospf dead-interval 40
!
interface eth2
 description "Link to leaf2"
 ip address 10.1.1.2/31
 ip ospf network point-to-point
 ip ospf hello-interval 10
 ip ospf dead-interval 40
!
interface eth3
 description "Link to leaf3"
 ip address 10.1.1.4/31
 ip ospf network point-to-point
 ip ospf hello-interval 10
 ip ospf dead-interval 40
!
interface eth4
 description "Link to leaf4"
 ip address 10.1.1.6/31
 ip ospf network point-to-point
 ip ospf hello-interval 10
 ip ospf dead-interval 40
!
router ospf
 ospf router-id 10.0.0.1
 log-adjacency-changes detail
 network 10.0.0.1/32 area 0
 network 10.1.1.0/31 area 0
 network 10.1.1.2/31 area 0
 network 10.1.1.4/31 area 0
 network 10.1.1.6/31 area 0
!
line vty
!
